In [1]:
import pandas as pd
import json
import numpy as np

In [2]:
LBL_FILE = '/home/lojze/data/datasets/LaRS/image_ann.json'

In [3]:
with open(LBL_FILE, 'r') as file:
    data = json.load(file)

In [4]:
data.keys()

dict_keys(['info', 'annotations', 'licenses'])

In [27]:
df_data = []
for ann in data['annotations']:
    d = {
        'image': ann['file_name'],
        'scene_type': ann['labels']['scene_type'],
        'lighting': ann['labels']['lighting'],
        'reflections': ann['labels']['reflections'],
        'waves': ann['labels']['waves'],
        'sp_extra_dark': ann['labels']['special']['extra_dark'],
        'sp_extra_bright': ann['labels']['special']['extra_bright'],
        'sp_glitter': ann['labels']['special']['glitter'],
        'sp_dirty_lens': ann['labels']['special']['dirty_lens'],
        'sp_wakes': ann['labels']['special']['wakes'],
        'sp_rain': ann['labels']['special']['rain'],
        'sp_fog': ann['labels']['special']['fog'],
        'sp_plants_debris': ann['labels']['special']['plants_debris'],
    }
    df_data.append(d)

df = pd.DataFrame(df_data).set_index('image')
df

,scene_type,lighting,reflections,waves,sp_extra_dark,sp_extra_bright,sp_glitter,sp_dirty_lens,sp_wakes,sp_rain,sp_fog,sp_plants_debris
image,,,,,,,,,,,,
yt010_15_00050.jpg,river_like,day_like,moderate,still,False,False,False,False,False,False,False,False
yt010_16_00050.jpg,river_like,day_like,heavy,still,False,False,False,False,False,False,False,False
yt010_17_00080.jpg,river_like,day_like,heavy,still,False,False,False,False,False,False,False,False
yt010_17_00050.jpg,river_like,day_like,heavy,still,False,False,False,False,False,False,False,False
yt010_16_00080.jpg,river_like,day_like,heavy,still,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
inhouse_MatejK_valun_MVI_5122_00800.jpg,sea_like,day_like,none,moderate,False,False,False,False,False,False,False,False
orca_flow_12_00220.jpg,sea_like,day_like,moderate,moderate,False,False,False,False,False,False,False,False
inhouse_MatejK_valun_MVI_5218_00200.jpg,sea_like,day_like,none,moderate,False,False,False,False,False,False,False,False
mastr_0540_00009.jpg,sea_like,day_like,none,moderate,False,False,False,False,False,False,False,False
mastr_0541_00009.jpg,sea_like,day_like,none,moderate,False,False,False,False,False,False,False,False

In [28]:
N = len(df)
N

4016

In [29]:
count = df['scene_type'].value_counts()
pd.concat([count, count / N], axis=1)

            scene_type  scene_type
sea_like          2879    0.716882
river_like        1136    0.282869

In [30]:
count = df['lighting'].value_counts()
pd.concat([count, count / N], axis=1)

            lighting  lighting
day_like        3854  0.959661
dusk_like        112  0.027888
night_like        50  0.012450

In [31]:
count = df['reflections'].value_counts()
pd.concat([count, count / N], axis=1)

          reflections  reflections
none             1941     0.483317
moderate         1918     0.477590
heavy             154     0.038347

In [32]:
count = df['waves'].value_counts()
pd.concat([count, count / N], axis=1)

          waves     waves
moderate   3700  0.921315
still       303  0.075448
rough        10  0.002490

In [33]:
sp_cols = [c for c in df.columns if c.startswith('sp_')]
sp_count = df[sp_cols].sum()
pd.concat([sp_count, sp_count / N], axis=1)

                    0         1
sp_extra_dark     617  0.153635
sp_extra_bright    44  0.010956
sp_glitter        263  0.065488
sp_dirty_lens      70  0.017430
sp_wakes          307  0.076444
sp_rain            23  0.005727
sp_fog            298  0.074203
sp_plants_debris  105  0.026145